// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: pkg/command/command.proto

package command

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type uint32 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	// Types that are assignable to Value:
	//	*Tag_Str
	//	*Tag_Int
	//	*Tag_Float
	//	*Tag_Bool
	Value isTag_Value `protobuf_oneof:"value"`
}

func (x *Tag) Reset() {
	*x = Tag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_command_command_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_command_command_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_pkg_command_command_proto_rawDescGZIP(), []int{0}
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tag) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (m *Tag) GetValue() isTag_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *Tag) GetStr() string {
	if x, ok := x.GetValue().(*Tag_Str); ok {
		return x.Str
	}
	return ""
}

func (x *Tag) GetInt() int64 {
	if x, ok := x.GetValue().(*Tag_Int); ok {
		return x.Int
	}
	return 0
}

func (x *Tag) GetFloat() int64 {
	if x, ok := x.GetValue().(*Tag_Float); ok {
		return x.Float
	}
	return 0
}

func (x *Tag) GetBool() bool {
	if x, ok := x.GetValue().(*Tag_Bool); ok {
		return x.Bool
	}
	return false
}

type isTag_Value interface {
	isTag_Value()
}

type Tag_Str struct {
	Str string `protobuf:"bytes,3,opt,name=str,proto3,oneof"`
}

type Tag_Int struct {
	Int int64 `protobuf:"zigzag64,4,opt,name=int,proto3,oneof"`
}

type Tag_Float struct {
	Float int64 `protobuf:"fixed64,5,opt,name=float,proto3,oneof"`
}

type Tag_Bool struct {
	Bool bool `protobuf:"varint,6,opt,name=bool,proto3,oneof"`
}

func (*Tag_Str) isTag_Value() {}

func (*Tag_Int) isTag_Value() {}

func (*Tag_Float) isTag_Value() {}

func (*Tag_Bool) isTag_Value() {}

type UpsertStatement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Types that are assignable to Value:
	//	*UpsertStatement_Str
	//	*UpsertStatement_Blob
	//	*UpsertStatement_Int
	//	*UpsertStatement_Bool
	Value              isUpsertStatement_Value `protobuf_oneof:"value"`
	Tags               []*Tag                  `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	PreserveTimestamps bool                    `protobuf:"varint,9,opt,name=preserve_timestamps,json=preserveTimestamps,proto3" json:"preserve_timestamps,omitempty"`
}

func (x *UpsertStatement) Reset() {
	*x = UpsertStatement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_command_command_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertStatement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertStatement) ProtoMessage() {}

func (x *UpsertStatement) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_command_command_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertStatement.ProtoReflect.Descriptor instead.
func (*UpsertStatement) Descriptor() ([]byte, []int) {
	return file_pkg_command_command_proto_rawDescGZIP(), []int{1}
}

func (x *UpsertStatement) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (m *UpsertStatement) GetValue() isUpsertStatement_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *UpsertStatement) GetStr() string {
	if x, ok := x.GetValue().(*UpsertStatement_Str); ok {
		return x.Str
	}
	return ""
}

func (x *UpsertStatement) GetBlob() []byte {
	if x, ok := x.GetValue().(*UpsertStatement_Blob); ok {
		return x.Blob
	}
	return nil
}

func (x *UpsertStatement) GetInt() int64 {
	if x, ok := x.GetValue().(*UpsertStatement_Int); ok {
		return x.Int
	}
	return 0
}

func (x *UpsertStatement) GetBool() bool {
	if x, ok := x.GetValue().(*UpsertStatement_Bool); ok {
		return x.Bool
	}
	return false
}

func (x *UpsertStatement) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpsertStatement) GetPreserveTimestamps() bool {
	if x != nil {
		return x.PreserveTimestamps
	}
	return false
}

type isUpsertStatement_Value interface {
	isUpsertStatement_Value()
}

type UpsertStatement_Str struct {
	Str string `protobuf:"bytes,2,opt,name=str,proto3,oneof"`
}

type UpsertStatement_Blob struct {
	Blob []byte `protobuf:"bytes,3,opt,name=blob,proto3,oneof"`
}

type UpsertStatement_Int struct {
	Int int64 `protobuf:"zigzag64,4,opt,name=int,proto3,oneof"`
}

type UpsertStatement_Bool struct {
	Bool bool `protobuf:"varint,5,opt,name=bool,proto3,oneof"`
}

func (*UpsertStatement_Str) isUpsertStatement_Value() {}

func (*UpsertStatement_Blob) isUpsertStatement_Value() {}

func (*UpsertStatement_Int) isUpsertStatement_Value() {}

func (*UpsertStatement_Bool) isUpsertStatement_Value() {}

type InsertStatement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Types that are assignable to Value:
	//	*InsertStatement_Str
	//	*InsertStatement_Blob
	//	*InsertStatement_Int
	//	*InsertStatement_Bool
	Value          isInsertStatement_Value `protobuf_oneof:"value"`
	WithTimestamps bool                    `protobuf:"varint,8,opt,name=with_timestamps,json=withTimestamps,proto3" json:"with_timestamps,omitempty"`
	ContentType    string                  `protobuf:"bytes,9,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
}

func (x *InsertStatement) Reset() {
	*x = InsertStatement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_command_command_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertStatement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertStatement) ProtoMessage() {}

func (x *InsertStatement) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_command_command_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertStatement.ProtoReflect.Descriptor instead.
func (*InsertStatement) Descriptor() ([]byte, []int) {
	return file_pkg_command_command_proto_rawDescGZIP(), []int{2}
}

func (x *InsertStatement) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (m *InsertStatement) GetValue() isInsertStatement_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *InsertStatement) GetStr() string {
	if x, ok := x.GetValue().(*InsertStatement_Str); ok {
		return x.Str
	}
	return ""
}

func (x *InsertStatement) GetBlob() []byte {
	if x, ok := x.GetValue().(*InsertStatement_Blob); ok {
		return x.Blob
	}
	return nil
}

func (x *InsertStatement) GetInt() int64 {
	if x, ok := x.GetValue().(*InsertStatement_Int); ok {
		return x.Int
	}
	return 0
}

func (x *InsertStatement) GetBool() bool {
	if x, ok := x.GetValue().(*InsertStatement_Bool); ok {
		return x.Bool
	}
	return false
}

func (x *InsertStatement) GetWithTimestamps() bool {
	if x != nil {
		return x.WithTimestamps
	}
	return false
}

func (x *InsertStatement) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type isInsertStatement_Value interface {
	isInsertStatement_Value()
}

type InsertStatement_Str struct {
	Str string `protobuf:"bytes,2,opt,name=str,proto3,oneof"`
}

type InsertStatement_Blob struct {
	Blob []byte `protobuf:"bytes,3,opt,name=blob,proto3,oneof"`
}

type InsertStatement_Int struct {
	Int int64 `protobuf:"zigzag64,4,opt,name=int,proto3,oneof"`
}

type InsertStatement_Bool struct {
	Bool bool `protobuf:"varint,5,opt,name=bool,proto3,oneof"`
}

func (*InsertStatement_Str) isInsertStatement_Value() {}

func (*InsertStatement_Blob) isInsertStatement_Value() {}

func (*InsertStatement_Int) isInsertStatement_Value() {}

func (*InsertStatement_Bool) isInsertStatement_Value() {}

type BatchUpsertRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Database string             `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Stmt     []*UpsertStatement `protobuf:"bytes,2,rep,name=stmt,proto3" json:"stmt,omitempty"`
	Timings  bool               `protobuf:"varint,3,opt,name=timings,proto3" json:"timings,omitempty"`
}

func (x *BatchUpsertRequest) Reset() {
	*x = BatchUpsertRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_command_command_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchUpsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUpsertRequest) ProtoMessage() {}

func (x *BatchUpsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_command_command_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUpsertRequest.ProtoReflect.Descriptor instead.
func (*BatchUpsertRequest) Descriptor() ([]byte, []int) {
	return file_pkg_command_command_proto_rawDescGZIP(), []int{3}
}

func (x *BatchUpsertRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *BatchUpsertRequest) GetStmt() []*UpsertStatement {
	if x != nil {
		return x.Stmt
	}
	return nil
}

func (x *BatchUpsertRequest) GetTimings() bool {
	if x != nil {
		return x.Timings
	}
	return false
}

type BatchInsertRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Database string             `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Stmt     []*InsertStatement `protobuf:"bytes,2,rep,name=stmt,proto3" json:"stmt,omitempty"`
	Timings  bool               `protobuf:"varint,3,opt,name=timings,proto3" json:"timings,omitempty"`
}

func (x *BatchInsertRequest) Reset() {
	*x = BatchInsertRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_command_command_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchInsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchInsertRequest) ProtoMessage() {}

func (x *BatchInsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_command_command_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchInsertRequest.ProtoReflect.Descriptor instead.
func (*BatchInsertRequest) Descriptor() ([]byte, []int) {
	return file_pkg_command_command_proto_rawDescGZIP(), []int{4}
}

func (x *BatchInsertRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *BatchInsertRequest) GetStmt() []*InsertStatement {
	if x != nil {
		return x.Stmt
	}
	return nil
}

func (x *BatchInsertRequest) GetTimings() bool {
	if x != nil {
		return x.Timings
	}
	return false
}

type BatchDeleteByKeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Database      string   `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Keys          []string `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	Timings       bool     `protobuf:"varint,3,opt,name=timings,proto3" json:"timings,omitempty"`
	IgnoreMissing bool     `protobuf:"varint,4,opt,name=ignore_missing,json=ignoreMissing,proto3" json:"ignore_missing,omitempty"`
}

func (x *BatchDeleteByKeyRequest) Reset() {
	*x = BatchDeleteByKeyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_command_command_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchDeleteByKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDeleteByKeyRequest) ProtoMessage() {}

func (x *BatchDeleteByKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_command_command_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDeleteByKeyRequest.ProtoReflect.Descriptor instead.
func (*BatchDeleteByKeyRequest) Descriptor() ([]byte, []int) {
	return file_pkg_command_command_proto_rawDescGZIP(), []int{5}
}

func (x *BatchDeleteByKeyRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *BatchDeleteByKeyRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *BatchDeleteByKeyRequest) GetTimings() bool {
	if x != nil {
		return x.Timings
	}
	return false
}

func (x *BatchDeleteByKeyRequest) GetIgnoreMissing() bool {
	if x != nil {
		return x.IgnoreMissing
	}
	return false
}

type ExecuteResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DocumentsAffected uint64   `protobuf:"varint,1,opt,name=documents_affected,json=documentsAffected,proto3" json:"documents_affected,omitempty"`
	Errors            []string `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	Elapsed           int64    `protobuf:"varint,3,opt,name=elapsed,proto3" json:"elapsed,omitempty"`
}

func (x *ExecuteResult) Reset() {
	*x = ExecuteResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_command_command_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResult) ProtoMessage() {}

func (x *ExecuteResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_command_command_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResult.ProtoReflect.Descriptor instead.
func (*ExecuteResult) Descriptor() ([]byte, []int) {
	return file_pkg_command_command_proto_rawDescGZIP(), []int{6}
}

func (x *ExecuteResult) GetDocumentsAffected() uint64 {
	if x != nil {
		return x.DocumentsAffected
	}
	return 0
}

func (x *ExecuteResult) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ExecuteResult) GetElapsed() int64 {
	if x != nil {
		return x.Elapsed
	}
	return 0
}

type Document struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Types that are assignable to Value:
	//	*Document_Str
	//	*Document_Blob
	//	*Document_Int
	//	*Document_Bool
	Value     isDocument_Value       `protobuf_oneof:"value"`
	Tags      []*Tag                 `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Type      string                 `protobuf:"bytes,8,opt,name=type,proto3" json:"type,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Document) Reset() {
	*x = Document{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_command_command_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_command_command_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_pkg_command_command_proto_rawDescGZIP(), []int{7}
}

func (x *Document) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (m *Document) GetValue() isDocument_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *Document) GetStr() string {
	if x, ok := x.GetValue().(*Document_Str); ok {
		return x.Str
	}
	return ""
}

func (x *Document) GetBlob() []byte {
	if x, ok := x.GetValue().(*Document_Blob); ok {
		return x.Blob
	}
	return nil
}

func (x *Document) GetInt() int64 {
	if x, ok := x.GetValue().(*Document_Int); ok {
		return x.Int
	}
	return 0
}

func (x *Document) GetBool() bool {
	if x, ok := x.GetValue().(*Document_Bool); ok {
		return x.Bool
	}
	return false
}

func (x *Document) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Document) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Document) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Document) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type isDocument_Value interface {
	isDocument_Value()
}

type Document_Str struct {
	Str string `protobuf:"bytes,2,opt,name=str,proto3,oneof"`
}

type Document_Blob struct {
	Blob []byte `protobuf:"bytes,3,opt,name=blob,proto3,oneof"`
}

type Document_Int struct {
	Int int64 `protobuf:"zigzag64,4,opt,name=int,proto3,oneof"`
}

type Document_Bool struct {
	Bool bool `protobuf:"varint,5,opt,name=bool,proto3,oneof"`
}

func (*Document_Str) isDocument_Value() {}

func (*Document_Blob) isDocument_Value() {}

func (*Document_Int) isDocument_Value() {}

func (*Document_Bool) isDocument_Value() {}

type MultiGetQueryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys          []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	Timings       bool     `protobuf:"varint,2,opt,name=timings,proto3" json:"timings,omitempty"`
	IgnoreMissing bool     `protobuf:"varint,3,opt,name=ignore_missing,json=ignoreMissing,proto3" json:"ignore_missing,omitempty"`
}

func (x *MultiGetQueryRequest) Reset() {
	*x = MultiGetQueryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_command_command_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiGetQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiGetQueryRequest) ProtoMessage() {}

func (x *MultiGetQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_command_command_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiGetQueryRequest.ProtoReflect.Descriptor instead.
func (*MultiGetQueryRequest) Descriptor() ([]byte, []int) {
	return file_pkg_command_command_proto_rawDescGZIP(), []int{8}
}

func (x *MultiGetQueryRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *MultiGetQueryRequest) GetTimings() bool {
	if x != nil {
		return x.Timings
	}
	return false
}

func (x *MultiGetQueryRequest) GetIgnoreMissing() bool {
	if x != nil {
		return x.IgnoreMissing
	}
	return false
}

type QueryResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Documents []*Document `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	Errors    []string    `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	Elapsed   float64     `protobuf:"fixed64,3,opt,name=elapsed,proto3" json:"elapsed,omitempty"`
}

func (x *QueryResult) Reset() {
	*x = QueryResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_command_command_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResult) ProtoMessage() {}

func (x *QueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_command_command_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResult.ProtoReflect.Descriptor instead.
func (*QueryResult) Descriptor() ([]byte, []int) {
	return file_pkg_command_command_proto_rawDescGZIP(), []int{9}
}

func (x *QueryResult) GetDocuments() []*Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *QueryResult) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *QueryResult) GetElapsed() float64 {
	if x != nil {
		return x.Elapsed
	}
	return 0
}

type Ping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Ping) Reset() {
	*x = Ping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_command_command_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_command_command_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_pkg_command_command_proto_rawDescGZIP(), []int{10}
}

func (x *Ping) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Pong struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Pong) Reset() {
	*x = Pong{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_command_command_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_command_command_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_pkg_command_command_proto_rawDescGZIP(), []int{11}
}

func (x *Pong) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_command_command_proto protoreflect.FileDescriptor

var file_pkg_command_command_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x63, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8c, 0x01, 0x0a, 0x03, 0x54, 0x61, 0x67, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x03, 0x73, 0x74, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x73, 0x74, 0x72, 0x12, 0x12, 0x0a, 0x03, 0x69, 0x6e, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x12, 0x48, 0x00, 0x52, 0x03, 0x69, 0x6e, 0x74, 0x12, 0x16, 0x0a,
	0x05, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x10, 0x48, 0x00, 0x52, 0x05,
	0x66, 0x6c, 0x6f, 0x61, 0x74, 0x12, 0x14, 0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6c, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x04, 0x62, 0x6f, 0x6f, 0x6c, 0x42, 0x07, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0xd3, 0x01, 0x0a, 0x0f, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x03, 0x73, 0x74,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x73, 0x74, 0x72, 0x12, 0x14,
	0x0a, 0x04, 0x62, 0x6c, 0x6f, 0x62, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x04,
	0x62, 0x6c, 0x6f, 0x62, 0x12, 0x12, 0x0a, 0x03, 0x69, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x12, 0x48, 0x00, 0x52, 0x03, 0x69, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6c,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x04, 0x62, 0x6f, 0x6f, 0x6c, 0x12, 0x20,
	0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x54, 0x61, 0x67, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73,
	0x12, 0x2f, 0x0a, 0x13, 0x70, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x12, 0x70,
	0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x73, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xcc, 0x01, 0x0a, 0x0f, 0x49,
	0x6e, 0x73, 0x65, 0x72, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x12, 0x0a, 0x03, 0x73, 0x74, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x03, 0x73, 0x74, 0x72, 0x12, 0x14, 0x0a, 0x04, 0x62, 0x6c, 0x6f, 0x62, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x48, 0x00, 0x52, 0x04, 0x62, 0x6c, 0x6f, 0x62, 0x12, 0x12, 0x0a, 0x03, 0x69, 0x6e,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x12, 0x48, 0x00, 0x52, 0x03, 0x69, 0x6e, 0x74, 0x12, 0x14,
	0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x04,
	0x62, 0x6f, 0x6f, 0x6c, 0x12, 0x27, 0x0a, 0x0f, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x77,
	0x69, 0x74, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x73, 0x12, 0x21, 0x0a,
	0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x78, 0x0a, 0x12, 0x42, 0x61, 0x74,
	0x63, 0x68, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x04, 0x73,
	0x74, 0x6d, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x2e, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x04, 0x73, 0x74, 0x6d, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d,
	0x69, 0x6e, 0x67, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x69,
	0x6e, 0x67, 0x73, 0x22, 0x78, 0x0a, 0x12, 0x42, 0x61, 0x74, 0x63, 0x68, 0x49, 0x6e, 0x73, 0x65,
	0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74,
	0x61, 0x62, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x61, 0x74,
	0x61, 0x62, 0x61, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x04, 0x73, 0x74, 0x6d, 0x74, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x49, 0x6e,
	0x73, 0x65, 0x72, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x04, 0x73,
	0x74, 0x6d, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x8a, 0x01,
	0x0a, 0x17, 0x42, 0x61, 0x74, 0x63, 0x68, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x79, 0x4b,
	0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74,
	0x61, 0x62, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x61, 0x74,
	0x61, 0x62, 0x61, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d,
	0x69, 0x6e, 0x67, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x69,
	0x6e, 0x67, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x5f, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x69, 0x67, 0x6e,
	0x6f, 0x72, 0x65, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x22, 0x70, 0x0a, 0x0d, 0x45, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x2d, 0x0a, 0x12, 0x64,
	0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x5f, 0x61, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x11, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x41, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6c, 0x61, 0x70, 0x73, 0x65, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6c, 0x61, 0x70, 0x73, 0x65, 0x64, 0x22, 0xa5, 0x02, 0x0a,
	0x08, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x03, 0x73,
	0x74, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x73, 0x74, 0x72, 0x12,
	0x14, 0x0a, 0x04, 0x62, 0x6c, 0x6f, 0x62, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52,
	0x04, 0x62, 0x6c, 0x6f, 0x62, 0x12, 0x12, 0x0a, 0x03, 0x69, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x12, 0x48, 0x00, 0x52, 0x03, 0x69, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x04, 0x62, 0x6f, 0x6f,
	0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x04, 0x62, 0x6f, 0x6f, 0x6c, 0x12,
	0x20, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x54, 0x61, 0x67, 0x52, 0x04, 0x74, 0x61, 0x67,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x42, 0x07, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x6b, 0x0a, 0x14, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x47, 0x65, 0x74,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x69, 0x67,
	0x6e, 0x6f, 0x72, 0x65, 0x5f, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0d, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6e,
	0x67, 0x22, 0x70, 0x0a, 0x0b, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x2f, 0x0a, 0x09, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x44, 0x6f,
	0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x09, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6c, 0x61,
	0x70, 0x73, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x65, 0x6c, 0x61, 0x70,
	0x73, 0x65, 0x64, 0x22, 0x20, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x20, 0x0a, 0x04, 0x50, 0x6f, 0x6e, 0x67, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xd1, 0x02, 0x0a, 0x08, 0x52, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x72, 0x12, 0x44, 0x0a, 0x0b, 0x42, 0x61, 0x74, 0x63, 0x68, 0x55, 0x70, 0x73,
	0x65, 0x72, 0x74, 0x12, 0x1b, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x0b, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x12, 0x1b, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00,
	0x12, 0x4e, 0x0a, 0x10, 0x42, 0x61, 0x74, 0x63, 0x68, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42,
	0x79, 0x4b, 0x65, 0x79, 0x12, 0x20, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x42,
	0x61, 0x74, 0x63, 0x68, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x79, 0x4b, 0x65, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00,
	0x12, 0x3d, 0x0a, 0x04, 0x4d, 0x47, 0x65, 0x74, 0x12, 0x1d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x47, 0x65, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12,
	0x2a, 0x0a, 0x08, 0x50, 0x69, 0x6e, 0x67, 0x50, 0x6f, 0x6e, 0x67, 0x12, 0x0d, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x1a, 0x0d, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x50, 0x6f, 0x6e, 0x67, 0x22, 0x00, 0x42, 0x2f, 0x5a, 0x2d, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x65, 0x6e, 0x69, 0x73, 0x6d,
	0x69, 0x74, 0x72, 0x2f, 0x6c, 0x65, 0x6d, 0x6f, 0x6e, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_command_command_proto_rawDescOnce sync.Once
	file_pkg_command_command_proto_rawDescData = file_pkg_command_command_proto_rawDesc
)

func file_pkg_command_command_proto_rawDescGZIP() []byte {
	file_pkg_command_command_proto_rawDescOnce.Do(func() {
		file_pkg_command_command_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_command_command_proto_rawDescData)
	})
	return file_pkg_command_command_proto_rawDescData
}

var file_pkg_command_command_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pkg_command_command_proto_goTypes = []interface{}{
	(*Tag)(nil),                     // 0: command.Tag
	(*UpsertStatement)(nil),         // 1: command.UpsertStatement
	(*InsertStatement)(nil),         // 2: command.InsertStatement
	(*BatchUpsertRequest)(nil),      // 3: command.BatchUpsertRequest
	(*BatchInsertRequest)(nil),      // 4: command.BatchInsertRequest
	(*BatchDeleteByKeyRequest)(nil), // 5: command.BatchDeleteByKeyRequest
	(*ExecuteResult)(nil),           // 6: command.ExecuteResult
	(*Document)(nil),                // 7: command.Document
	(*MultiGetQueryRequest)(nil),    // 8: command.MultiGetQueryRequest
	(*QueryResult)(nil),             // 9: command.QueryResult
	(*Ping)(nil),                    // 10: command.Ping
	(*Pong)(nil),                    // 11: command.Pong
	(*timestamppb.Timestamp)(nil),   // 12: google.protobuf.Timestamp
}
var file_pkg_command_command_proto_depIdxs = []int32{
	0,  // 0: command.UpsertStatement.tags:type_name -> command.Tag
	1,  // 1: command.BatchUpsertRequest.stmt:type_name -> command.UpsertStatement
	2,  // 2: command.BatchInsertRequest.stmt:type_name -> command.InsertStatement
	0,  // 3: command.Document.tags:type_name -> command.Tag
	12, // 4: command.Document.created_at:type_name -> google.protobuf.Timestamp
	12, // 5: command.Document.updated_at:type_name -> google.protobuf.Timestamp
	7,  // 6: command.QueryResult.documents:type_name -> command.Document
	3,  // 7: command.Receiver.BatchUpsert:input_type -> command.BatchUpsertRequest
	4,  // 8: command.Receiver.BatchInsert:input_type -> command.BatchInsertRequest
	5,  // 9: command.Receiver.BatchDeleteByKey:input_type -> command.BatchDeleteByKeyRequest
	8,  // 10: command.Receiver.MGet:input_type -> command.MultiGetQueryRequest
	10, // 11: command.Receiver.PingPong:input_type -> command.Ping
	6,  // 12: command.Receiver.BatchUpsert:output_type -> command.ExecuteResult
	6,  // 13: command.Receiver.BatchInsert:output_type -> command.ExecuteResult
	6,  // 14: command.Receiver.BatchDeleteByKey:output_type -> command.ExecuteResult
	9,  // 15: command.Receiver.MGet:output_type -> command.QueryResult
	11, // 16: command.Receiver.PingPong:output_type -> command.Pong
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_pkg_command_command_proto_init() }
func file_pkg_command_command_proto_init() {
	if File_pkg_command_command_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_command_command_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_command_command_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpsertStatement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_command_command_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertStatement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_command_command_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchUpsertRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_command_command_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchInsertRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_command_command_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchDeleteByKeyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_command_command_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_command_command_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Document); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_command_command_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiGetQueryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_command_command_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_command_command_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_command_command_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pong); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pkg_command_command_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Tag_Str)(nil),
		(*Tag_Int)(nil),
		(*Tag_Float)(nil),
		(*Tag_Bool)(nil),
	}
	file_pkg_command_command_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*UpsertStatement_Str)(nil),
		(*UpsertStatement_Blob)(nil),
		(*UpsertStatement_Int)(nil),
		(*UpsertStatement_Bool)(nil),
	}
	file_pkg_command_command_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*InsertStatement_Str)(nil),
		(*InsertStatement_Blob)(nil),
		(*InsertStatement_Int)(nil),
		(*InsertStatement_Bool)(nil),
	}
	file_pkg_command_command_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*Document_Str)(nil),
		(*Document_Blob)(nil),
		(*Document_Int)(nil),
		(*Document_Bool)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_command_command_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_command_command_proto_goTypes,
		DependencyIndexes: file_pkg_command_command_proto_depIdxs,
		MessageInfos:      file_pkg_command_command_proto_msgTypes,
	}.Build()
	File_pkg_command_command_proto = out.File
	file_pkg_command_command_proto_rawDesc = nil
	file_pkg_command_command_proto_goTypes = nil
	file_pkg_command_command_proto_depIdxs = nil
}
